---
- name: Create manifests directory for temp configuration
  file:
    path: /tmp/k3s
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0755
  with_items: "{{ groups[group_name_master | default('master')] }}"
  run_once: true

- name: Install reflector and replicator
  command: "{{ item }}"
  register: this
  changed_when: false
  with_items:
  - k3s kubectl apply -f https://raw.githubusercontent.com/mittwald/kubernetes-replicator/master/deploy/rbac.yaml
  - k3s kubectl apply -f https://raw.githubusercontent.com/mittwald/kubernetes-replicator/master/deploy/deployment.yaml
  - k3s kubectl -n kube-system apply -f https://github.com/emberstack/kubernetes-reflector/releases/latest/download/reflector.yaml
  run_once: true
  until: this.rc == 0
  retries: 5

- name: Copy wild card certificate config to first master
  template:
    src: "wildcard-cert.yaml.j2"
    dest: "/tmp/k3s/wildcard-cert.yaml"
    owner: root
    group: root
    mode: 0755
  with_items: "{{ groups[group_name_master | default('master')] }}"
  run_once: true

- name: Create wild-card-certificate
  command: >-
    k3s kubectl apply -f /tmp/k3s/wildcard-cert.yaml
  register: this
  changed_when: false
  run_once: true
  until: this.rc == 0
  retries: 5