---
- name: Create external-dns namespace
  command: >-
    k3s kubectl create namespace externaldns
  register: this
  changed_when: false
  run_once: true
  until: this.rc == 0
  retries: 5

- name: Create external-dns password secret
  command: >-
    k3s kubectl create secret generic pihole-password --from-literal EXTERNAL_DNS_PIHOLE_PASSWORD={{ externaldns_password }} -n externaldns
  register: this
  changed_when: false
  run_once: true
  until: this.rc == 0
  retries: 5

- name: Copy externaldns manifest to first master
  template:
    src: "externaldns.yaml.j2"
    dest: "/tmp/k3s/externaldns.yaml"
    owner: "{{ ansible_user_id }}"
    mode: 0755
  with_items: "{{ groups[group_name_master | default('master')] }}"
  run_once: true

- name: Install externaldns
  command: >-
    k3s kubectl apply -f /tmp/k3s/externaldns.yaml -n externaldns
  register: this
  changed_when: false
  run_once: true
  until: this.rc == 0
  retries: 5