---
- name: Copy all-apps-ingress.yaml to master
  template:
    src: "apps-ingress-setup.yaml.j2"
    dest: "/tmp/k3s/apps-ingress-setup.yaml"
    owner: "{{ ansible_user_id }}"
    mode: 0755
  with_items: "{{ groups[group_name_master | default('master')] }}"
  run_once: true

- name: Create Ingresses for apps
  command: >-
    k3s kubectl apply -f /tmp/k3s/apps-ingress-setup.yaml
  register: this
  changed_when: false
  run_once: true
  until: this.rc == 0
  retries: 5