---
- name: Deploy metallb pool
  include_tasks: metallb.yml
  tags: metallb

- name: Deploy cluster issuer 
  include_tasks: cert_manager.yml
  tags: cert-manager

- name: Deploy argocd 
  include_tasks: argocd.yml
  tags: argocd

- name: Deploy external dns 
  include_tasks: externaldns.yml
  tags: externaldns

- name: Deploy other utils 
  include_tasks: generic.yml


- name: Remove tmp directory used for manifests
  file:
    path: /tmp/k3s
    state: absent
